### ISSUE TITLE
Symfony implementation?

### ISSUE THREAD

**Issue by rubtsovi** [JanDC/critical-css#5]
Hello,
in posts about your library you wrote that you're working on it. So how it looks :) ? Is it possible to be released in future?
Thanks.

**Comment by JanDC** [comment]
Hi @rubtsovi! (sorry for the late reply)

The Symfony implementation has been put on hold, due to time constraints.
It will probably be picked up some time in the (as yet to be determined) future.

If you're keen to make an implementation yourself, I'd be more that happy to support you in that endeavor 😄 .
